# Generated by Django 6.0.7 on 2026-07-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('syllabus_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('certification', models.CharField(max_length=255)),
                ('exam_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradedAssessment',
            fields=[
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='graded_assessment', serialize=False, to='courses.assessment')),
                ('payload', models.JSONField()),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('roadmap_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='courses.assessment')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='courses.syllabus')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.syllabus'),
        ),
    ]
