"""llm_engine: LLM pipeline for adaptive certification course generation.

Public API: the four stage functions, the pipeline orchestrator, all
domain schemas, and the typed exceptions.
"""

from llm_engine.exceptions import LLMCallError, LLMEngineError, StructuredOutputError
from llm_engine.schemas import (
    Assessment,
    Course,
    DomainScore,
    ExamDomain,
    FillInBlankLLMQuestion,
    FillInBlankQuestion,
    FullTextLLMQuestion,
    FullTextQuestion,
    GradedAssessment,
    KnowledgeGap,
    Lesson,
    LessonExample,
    LessonPracticeQuestion,
    LessonSection,
    MultiAnswerLLMQuestion,
    MultiAnswerQuestion,
    Question,
    QuestionOption,
    QuestionResult,
    QuestionType,
    QuestionTypeWeight,
    Roadmap,
    RoadmapItem,
    SingleAnswerLLMQuestion,
    SingleAnswerQuestion,
    SkippedDomain,
    StudyWeek,
    Syllabus,
    UserAnswer,
)
from llm_engine.services import (
    generate_assessment,
    generate_course,
    generate_lesson,
    generate_roadmap,
    generate_syllabus,
    grade_assessment,
    run_full_pipeline,
)

__all__ = [
    "Assessment",
    "Course",
    "DomainScore",
    "ExamDomain",
    "FillInBlankLLMQuestion",
    "FillInBlankQuestion",
    "FullTextLLMQuestion",
    "FullTextQuestion",
    "GradedAssessment",
    "KnowledgeGap",
    "Lesson",
    "LessonExample",
    "LessonPracticeQuestion",
    "LessonSection",
    "LLMCallError",
    "LLMEngineError",
    "MultiAnswerLLMQuestion",
    "MultiAnswerQuestion",
    "Question",
    "QuestionOption",
    "QuestionResult",
    "QuestionType",
    "QuestionTypeWeight",
    "Roadmap",
    "RoadmapItem",
    "SingleAnswerLLMQuestion",
    "SingleAnswerQuestion",
    "SkippedDomain",
    "StructuredOutputError",
    "StudyWeek",
    "Syllabus",
    "UserAnswer",
    "generate_assessment",
    "generate_course",
    "generate_lesson",
    "generate_roadmap",
    "generate_syllabus",
    "grade_assessment",
    "run_full_pipeline",
]
